urls.py
from django.conf.urls import url
from django.views.defaults import page_not_found

from . import views

urlpatterns = [
    url(r'^$',
        views.cal_redirect,
        name="index"),

    url(r'^cal/$',
        views.cal_redirect,
        name="calendar_redirect"),

    url(r'^profiles/$',
        views.ProfileList.as_view(),
        name="profile_list"),

    url(r'^profiles/settings/$',
        views.ProfileUpdate.as_view(),
        name="profile_update"),

    url(r'^profiles/users/(?P<user_id>\d+)/rm/$',
        views.profile_remove_user,
        name="profile_remove_user"),

    url(r'^profiles/create/$',
        views.ProfileCreate.as_view(),
        name="profile_create"),

    url(r'^profiles/(?P<pk>\d+)/$',
        views.profile_select,
        name="profile_select"),

    url(r'^consumers/$',
        views.ConsumerList.as_view(),
        name="consumer_list"),

    url(r'^consumers/(?P<pk>\d+)/$',
        views.ConsumerDetail.as_view(),
        name="consumer_detail"),

    url(r'^consumers/(?P<pk>\d+)/delete/$',
        views.ConsumerDelete.as_view(),
        name="consumer_delete"),

    url(r'^consumers/create/$',
        views.ConsumerCreate.as_view(),
        name="consumer_create"),

    url(r'^calendar/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        views.MealMonthArchive.as_view(month_format='%m'),
        name="calendar"),

    url(r'^calendar/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/all/$',
        views.MealMonthArchiveFull.as_view(month_format='%m'),
        name="calendar_all"),

    url(r'^meals/date/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        views.MealDayArchive.as_view(month_format='%m'),
        name="meal_day"),

    url(r'^meals/date/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/(?P<meal_type>\d+)/$',
        views.MealDayArchiveSpecific.as_view(month_format='%m'),
        name="meal_day_spec"),

    url(r'^meals/(?P<pk>\d+)/$',
        views.MealDetail.as_view(),
        name="meal_detail"),

    url(r'^meals/create/$',
        views.MealCreate.as_view(),
        name="meal_create"),

    url(r'^meals/delete/(?P<pk>\d+)/$',
        views.MealDelete.as_view(),
        name="meal_delete"),

    url(r'^dishes/create/$',
        views.DishCreate.as_view(),
        name="dish_create"),

    url(r'^dishes/delete/(?P<pk>\d+)/$',
        views.DishDelete.as_view(),
        name="dish_delete"),

    url(r'^inventory/$',
        views.IngredientList.as_view(),
        name="inventory"),

    url(r'^inventory/all/$',
        views.IngredientListFull.as_view(),
        name="inventory_all"),

    url(r'^ingredients/(?P<pk>\d+)/$',
        views.IngredientDetail.as_view(),
        name="ingredient_detail"),

    url(r'^ingredient/create/$',
        views.IngredientCreate.as_view(),
        name="ingredient_create"),

    url(r'^units/$',
        views.UnitList.as_view(),
        name="unit_list"),

    url(r'^units/create/$',
        views.UnitCreate.as_view(),
        name="unit_create"),

    url(r'^categories/$',
        views.CategoryList.as_view(),
        name="category_list"),

    url(r'^categories/create/$',
        views.CategoryCreate.as_view(),
        name="category_create"),

    url(r'^vendors/$',
        views.VendorList.as_view(),
        name="vendor_list"),

    url(r'^vendors/create/$',
        views.VendorCreate.as_view(),
        name="vendor_create"),

    url(r'^products/$',
        views.ProductList.as_view(),
        name="product_list"),

    url(r'^products/raw/(?P<pk>\d+)/$',
        views.product_raw,
        name="product_raw"),

    url(r'^products/raw/$',
        page_not_found,     # FIXME
        name="product_raw_noid"),

    url(r'^products/create/$',
        views.ProductCreate.as_view(),
        name="product_create"),

    url(r'^ticket/create/$',
        views.ticket_create,
        name="ticket_create"),

    url(r'^ticket/delete/(?P<pk>\d+)/$',
        views.TicketDelete.as_view(),
        name="ticket_delete"),
]

models.py
from datetime import date
from decimal import Decimal

from django.contrib.auth.models import User
from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from djmoney.models.fields import CurrencyField, MoneyField
from moneyed import Money


@python_2_unicode_compatible
class GrainEvent(models.Model):
    CREATE, EDIT, DELETE = "creation", "update", "deletion"
    LOG_ACTIONS = (
        (CREATE, "Create"),
        (EDIT, "Edit"),
        (DELETE, "Delete")
    )

    action = models.CharField(choices=LOG_ACTIONS, max_length=20)
    model = models.CharField(max_length=30)
    object_pk = models.IntegerField()
    user = models.ForeignKey(User)
    time = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s %s (%s)" % (self.model, self.action, self.user)


@python_2_unicode_compatible
class UserProfile(models.Model):
    """Profile for Grain

    A profile will handle ingredients and meals in a single currency.
    """
    user = models.ManyToManyField(User)
    note = models.CharField(max_length=24)
    currency = CurrencyField(default='GBP')

    def add_user(self, user):
        self.user.add(user)

    def __str__(self):
        return "%s: %s" % (self.currency, self.note)


@python_2_unicode_compatible
class Consumer(models.Model):
    owner = models.ForeignKey(UserProfile)
    actual_user = models.ForeignKey(User, blank=True, null=True)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Unit(models.Model):
    """Custom unit class for groceries"""
    short = models.CharField("abbreviation", max_length=8)
    verbose = models.CharField("name (singular)", max_length=20)
    plural = models.CharField(max_length=20)

    def __str__(self):
        return self.short


@python_2_unicode_compatible
class IngredientCategory(models.Model):
    """Cascading categories for ingredients"""
    parent = models.ForeignKey('self', default=None, blank=True, null=True)
    name = models.CharField(max_length=40)

    def get_parent_name_list(self):
        li = self.parent.get_parent_name_list() if self.parent else []
        li.append(self.name)
        return li

    class Meta:
        verbose_name_plural = "ingredient categories"

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Vendor(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Product(models.Model):
    """Classes of ingredients, in specific units and packaging"""
    name = models.CharField(max_length=60)
    vendor = models.ForeignKey(Vendor, blank=True, null=True, default=None)
    category = models.ForeignKey(IngredientCategory)
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='GBP')
    amount = models.FloatField()
    units = models.ForeignKey(Unit)
    fixed = models.BooleanField(default=True)

    def get_vendor(self):
        return self.vendor if self.vendor else "Other"

    def __str__(self):
        if not self.fixed:
            return "%s %s" % (self.get_vendor(), self.name)
        return "%s %s (%g%s)" % (self.get_vendor(), self.name, self.amount,
                                 self.units)


@python_2_unicode_compatible
class Ingredient(models.Model):
    """Specific instances of ingredients"""
    BEST_BEFORE, EXPIRES = "BBF", "EXP"
    EXP_CHOICES = (
        (BEST_BEFORE, "best before"),
        (EXPIRES, "expires")
    )

    owner = models.ForeignKey(UserProfile)
    product = models.ForeignKey(Product)
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='GBP')
    amount = models.FloatField()
    used_amount = models.FloatField(default=0)
    best_before = models.DateField(blank=True)
    expiry_type = models.CharField(max_length=3, choices=EXP_CHOICES)
    purchase_date = models.DateField(default=date.today)
    exhausted = models.BooleanField(default=False)

    def update_usage(self, delta):
        assert not self.exhausted, "Ingredient has been exhausted"

        self.used_amount += delta
        if self.used_amount != 0:
            cpu = self.price * (1 / self.used_amount)
        else:
            cpu = Money(0, self.price.currency.code)
        for ticket in self.ticket_set.all():
            ticket.update_cost(cpu)
        self.save()
        return cpu

    def set_exhausted(self, exhausted):
        if exhausted != self.exhausted:
            for ticket in self.ticket_set.all():
                ticket.set_final(exhausted)
            self.exhausted = exhausted
            self.save()

    def __str__(self):
        return "%s %s (%g %s:%s)" % (self.product.get_vendor(),
                                     self.product.name, self.amount,
                                     self.product.units, self.used_amount)


@python_2_unicode_compatible
class Meal(models.Model):
    # FIXME: include docstring
    BREAKFAST, LUNCH, DINNER, SUPPER, TEA, SNACK = 0, 1, 2, 3, 4, 5
    MEAL_CHOICES = (
        (BREAKFAST, "Breakfast"),
        (LUNCH,     "Lunch"),
        (DINNER,    "Dinner"),
        (SUPPER,    "Supper"),
        (TEA,       "Tea"),
        (SNACK,     "Snack"),
    )
    owner = models.ForeignKey(UserProfile)
    time = models.DateTimeField()
    meal_type = models.IntegerField(choices=MEAL_CHOICES)
    cost_closed = MoneyField(max_digits=10, decimal_places=4)
    cost_open = MoneyField(max_digits=10, decimal_places=4)
    consumer = models.ForeignKey(Consumer)

    def cost_progress_breakdown(self):
        cost_tot, pc_closed, pc_open = self.cost_closed + self.cost_open, 0, 0
        if cost_tot:
            pc_closed = 100 * self.cost_closed.amount / cost_tot.amount
            pc_open = 100 * self.cost_open.amount / cost_tot.amount
        return (cost_tot, pc_closed, pc_open)

    def __str__(self):
        return "%s on %s" % (self.get_meal_type_display(), self.time.strftime("%F"))


@python_2_unicode_compatible
class Dish(models.Model):
    # FIXME: include docstring
    COOKING_STYLES = (
        ('frying',      "Fried"),
        ('boiling',     "Boiled"),
        ('poaching',    "Poached"),
        ('baking',      "Baked"),
        ('roasting',    "Roasted"),
        ('uncooked',    "Uncooked"),
        ('instant',     "Microwaved")
    )
    method = models.CharField(max_length=8, choices=COOKING_STYLES)
    meal = models.ForeignKey(Meal)
    cost_closed = MoneyField(max_digits=10, decimal_places=4)
    cost_open = MoneyField(max_digits=10, decimal_places=4)

    def costs_open_change(self, delta):
        self.cost_open += delta
        self.save()

        self.meal.cost_open += delta
        self.meal.save()

    def costs_close(self, delta):
        self.cost_closed += delta
        self.cost_open -= delta
        self.save()

        self.meal.cost_closed += delta
        self.meal.cost_open -= delta
        self.meal.save()

    def get_ticket_form(self, profile_pk=None):
        from .forms import TicketForm
        return TicketForm(profile_pk, initial={'dish': self})

    class Meta:
        verbose_name_plural = "dishes"

    def __str__(self):
        tickets = self.ticket_set.all().order_by('-cost')
        if tickets.distinct().count() == 0:
            return "%s (empty)" % self.method
        return "%s %s" % (self.get_method_display(), tickets[0])


class TicketManager(models.Manager):
    def create_ticket(self, ingredient, used_on_ticket, dish, currency,
                      exhausted=False):
        assert used_on_ticket > 0, "Must use positive quantity"
        assert not ingredient.exhausted, "Ingredient must not be exhausted"

        ticket = self.create(ingredient=ingredient, used=0,
                             dish=dish, cost=Money(0, currency))
        ticket.update_usage(used_on_ticket)
        if exhausted:
            ingredient.set_exhausted(True)
        return ticket


@python_2_unicode_compatible
class Ticket(models.Model):
    # FIXME: include docstring
    objects = TicketManager()

    ingredient = models.ForeignKey(Ingredient)
    used = models.FloatField()
    cost = MoneyField(max_digits=10, decimal_places=4)
    final = models.BooleanField(default=False)
    dish = models.ForeignKey(Dish)

    def update_usage(self, delta):
        self.used += delta
        self.save()
        self.ingredient.update_usage(delta)

    def update_cost(self, cost_per_unit):
        assert not self.final, "Cannot modify finalised tickets"
        new_cost = self.used * cost_per_unit
        self.dish.costs_open_change(new_cost - self.cost)
        self.cost = new_cost
        self.save()

    def set_final(self, final):
        if final != self.final:
            if final:
                self.dish.costs_close(self.cost)
            else:
                self.dish.costs_close(-self.cost)
            self.final = final
            self.save()

    def __str__(self):
        return "%s [%s]" % (self.ingredient, self.used)


@receiver(signals.pre_delete, sender=Ticket)
def clean_ticket(sender, **kwargs):
    ticket = kwargs.get('instance')
    was_final = ticket.final

    if was_final:
        ticket.ingredient.set_exhausted(False)
        ticket.final = False

    ticket.update_usage(-ticket.used)

    if was_final:
        ticket.ingredient.set_exhausted(True)

templates/grain/consumer_detail.html
{% extends "grain/base.html" %}

{% block title %}Grain: Consumer{% endblock %}

{% block content %}
<h1>Consumer</h1>
<a href="{% url 'grain:consumer_list' %}" role="button" class="btn btn-link">&laquo; Consumer List</a>
<h2>{{ object }}{% if object.actual_user %} <small>{{ object.actual_user }}</small>{% endif %}</h2>
<h3>Meal list</h3>

<div class="col-md-8">
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <th>Meal</th>
        <th>Cost</th>
        <th>Dishes</th>
      </thead>
      <tbody>
        {% for meal in object.meal_set.all|dictsort:"time" %}
        <tr>
          <td><a href="{% url "grain:meal_detail" meal.id %}">{{ meal }}</a></td>
          <td>
            {{ meal.cost_progress_breakdown.0 }}
            <div class="progress" style="max-width: 12em;">
              <div class="progress-bar progress-bar-success" style="width: {{ meal.cost_progress_breakdown.1 }}%;">{{ meal.cost_closed.amount|floatformat:2 }}</div>
              <div class="progress-bar progress-bar-danger" style="width: {{ meal.cost_progress_breakdown.2 }}%;">{{ meal.cost_open.amount|floatformat:2 }}</div>
            </div>
          </td>
          <td>
            <ul>
              {% for dish in meal.dish_set.all %}
              <li>{{ dish }}</li>
              {% endfor %}
            </ul>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="3" style="text-align: center; font-weight: 700;">No meals</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

templates/grain/consumer_form.html
{% extends "grain/base.html" %}
{% load bootstrap3 %}

{% block title %}Grain: New Consumer{% endblock %}

{% block content %}
<h1>New Consumer</h1>

<div class="col-md-4">
  <form method="post" action="{% url 'grain:consumer_create' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Create</button>
    {% endbuttons %}
  </form>
</div>
{% endblock content %}

templates/grain/dish_confirm_delete.html
{% extends "grain/base.html" %}
{% load bootstrap3 %}

{% block title %}Grain: Delete Dish{% endblock %}

{% block content %}
<h1>Delete Dish</h1>
<h2>{{ object }}</h2>

<div class="row">
  <div class="col-md-4">
    <h3>Info</h3>
    <div class="table-responsive">
      <table class="table table-striped">
        <tbody>
          <tr>
            <td>Meal</td>
            <td>{{ object.meal }}</td>
          </tr>
          <tr>
            <td>Method</td>
            <td>{{ object.get_method_display }}</td>
          </tr>
          <tr>
            <td>Cost</td>
            <td>Confirmed: {{ object.cost_closed }}<br>Open: {{ object.cost_open }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-8">
    <h3>Confirm</h3>
    <form action="" method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete <strong>{{ object }}</strong>?</p>
      {% if object.ticket_set.all %}
      <p>You will also delete the following tickets (costs will be reassigned for the ingredients):</p>
      <ul>
        {% for ticket in object.ticket_set.all %}
        <li><a href="{% url 'grain:ingredient_detail' ticket.ingredient.pk %}">{{ ticket }}</a> &mdash; {{ ticket.cost }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      {% buttons %}
      <button type="submit" class="btn btn-danger">Delete</button>
      {% endbuttons %}
    </form>
  </div>
</div>
{% endblock content %}

templates/grain/generic_form.html
{% extends "grain/base.html" %}
{% load bootstrap3 %}

{% block content %}
<h1>Form</h1>

<div class="col-md-4">
  <form method="post" action="">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
  </form>
</div>
{% endblock content %}

templates/grain/ingredient_list.html
{% extends "grain/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title %}Grain: Inventory{% endblock %}

{% block scripts %}
<link href="{% static 'bootstrap-calendar/calendar.css' %}" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.9/select2-bootstrap.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

<script>
$(document).ready(function() {
  $('.datepicker').datepicker({
    format: 'yyyy-mm-dd',
    weekStart: 1,
    autoclose: true,
    disableTouchKeyboard: true,
    todayHighlight: true,
  });
});
</script>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
  loaded = false;
  g_data = null;
  $('#{{ ingredient_form.amount.auto_id }}').prop('disabled', true);

  $('#{{ ingredient_form.product.auto_id }}').on('change', function(e){
    if (!$('#{{ ingredient_form.partial.auto_id }}').prop('checked')){
      $('#{{ ingredient_form.amount.auto_id }}').prop('disabled', true);
    }
    if ($(this).val()){
      $.get(  "{% url 'grain:product_raw_noid' %}" + $(this).val(),
      function(data){
        g_data = jQuery.parseJSON(data);
        loaded = true;
        $('#{{ ingredient_form.price.auto_id }}_0').val(g_data.usual_price);
        $('#{{ ingredient_form.price.auto_id }}_0').change();
        $('#{{ ingredient_form.amount.auto_id }}').val(g_data.amount);
        document.querySelector('label[for="{{ ingredient_form.amount.id_for_label }}"]').textContent = 'Amount (' + g_data.units + ')';
      });
    } else {
      $('#{{ ingredient_form.price.auto_id }}_0').val("0.00");
      $('#{{ ingredient_form.amount.auto_id }}').val("0.00");
      loaded = false;
    }
    e.preventDefault();
  });
  $('#{{ ingredient_form.price.auto_id }}_0').on('change', function(e){
    if (loaded && !g_data.fixed) {
      $('#{{ ingredient_form.amount.auto_id }}').val(Math.round(g_data.amount / g_data.usual_price * 100 * $('#{{ ingredient_form.price.auto_id }}_0').val()) / 100);
      $('#{{ ingredient_form.amount.auto_id }}').prop('disabled', false);
    }
  });
  $('#{{ ingredient_form.partial.auto_id }}').on('change', function(e){
    if ($('#{{ ingredient_form.partial.auto_id }}').prop('checked')){
      $('#{{ ingredient_form.amount.auto_id }}').prop('disabled', false);
    }
  });
});//]]>
</script>
<script type="text/javascript">
$(document).ready(function() {
  $.fn.select2.defaults.set( "theme", "bootstrap" );
  $("#{{ ingredient_form.product.auto_id }}").select2({
    placeholder: "Select a product",
    allowClear: true,
  });
  $("#{{ ingredient_form.product.auto_id }}").val(null).trigger("change");

  $("#{{ ingredient_form.price.auto_id }}_1").prop("disabled", true);
  $("form").bind('submit', function(){
    $("#{{ ingredient_form.price.auto_id }}_1").prop("disabled", false);
  });
});
</script>
{% endblock scripts %}

{% block content %}
<h1>Inventory</h1>

<div class="row">
  <div class="col-md-3">
    <h2>Add item</h2>
    <form method="post" action="{% url 'grain:ingredient_create' %}">
      {% csrf_token %}
      {% bootstrap_form ingredient_form %}
      {% buttons %}
      <button type="submit" class="btn btn-primary">Create</button>
      {% endbuttons %}
    </form>
  </div>

  <div class="col-md-9">
    <h2>Contents{% if full %} (historical){% endif %}</h2>
    <ul class="nav nav-tabs">
      {% if full %}
      <li role="presentation"><a href="{% url 'grain:inventory' %}" role="button" class="btn btn-link">Current Items</a></li>
      <li role="presentation" class="active"><a href="#" role="button" class="btn btn-link">All Items</a></li>
      {% else %}
      <li role="presentation" class="active"><a href="#" role="button" class="btn btn-link">Current Items</a></li>
      <li role="presentation"><a href="{% url 'grain:inventory_all' %}" role="button" class="btn btn-link">All Items</a></li>
      {% endif %}
    </ul>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <th>Product</th>
          <th>Amount</th>
          <th>Cost</th>
          <th>Used</th>
          <th>Best Before</th>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr class="{% if object.exhausted %}danger{% endif %}">
            <td><a href="{% url 'grain:ingredient_detail' object.pk %}">{{ object.product }}</a></td>
            <td>{{ object.amount }} {{ object.product.units }}</td>
            <td>{{ object.price }}</td>
            <td>{{ object.used_amount }}</td>
            <td>{{ object.best_before }}</td>
          </tr>
          {% endfor %}
          {% if full %}
          <tr class="danger">
            <td colspan="5" style="text-align: center; font-size: .9em; font-style: italic;">exhausted items highlighted</td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

templates/grain/meal_archive_day.html
{% extends "grain/base.html" %}

{% block title %}Grain: Meals on {{ day|date:"jS F Y" }}{% endblock %}

{% block content %}
<h1>Meals <small>{{ day|date:"jS F Y" }}</small></h1>
<a href="{% url 'grain:calendar' day.year day.month %}" role="button" class="btn btn-link">&laquo; Calendar</a>

<div class="row">
  <div class="col-md-8">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <th>Cost</th>
          <th>Dishes</th>
          <th>Consumer</th>
        </thead>
        <tbody>
          {% for meal in object_list|dictsort:"meal_type" %}
          {% ifchanged meal.meal_type %}
          <tr>
            <td colspan="3" style="text-align: center; font-weight: 700;">{{ meal.get_meal_type_display }}</td>
          </tr>
          {% endifchanged %}
          <tr>
            <td>
              <a href="{% url "grain:meal_detail" meal.id %}">{{ meal.cost_progress_breakdown.0 }}</a>
              <div class="progress" style="max-width: 12em;">
                <div class="progress-bar progress-bar-success" style="width: {{ meal.cost_progress_breakdown.1 }}%;">{{ meal.cost_closed.amount|floatformat:2 }}</div>
                <div class="progress-bar progress-bar-danger" style="width: {{ meal.cost_progress_breakdown.2 }}%;">{{ meal.cost_open.amount|floatformat:2 }}</div>
              </div>
            </td>
            <td>
              <ul>
                {% for dish in meal.dish_set.all %}
                <li>{{ dish }}</li>
                {% endfor %}
              </ul>
            </td>
            <td>{{ meal.consumer|default_if_none:"self" }}</td>
          </tr>
          {% endfor %}
          {% if specific %}
          <tr class="danger">
            <td colspan="3" style="text-align: center; font-size: .9em; font-style: italic;">only showing one mealtime</td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

templates/grain/nav.html
{% load radix_extras %}
{% load grain_extras %}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header navbar-collapse collapse">
      <a class="navbar-brand" href="{% url 'radix:index' %}">Grain</a>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li class="{% nav_active request 'grain:index' %}"><a href="{% url 'grain:index' %}">Calendar</a></li>
        <li class="{% nav_active request 'grain:inventory grain:inventory_all' %}"><a href="{% url 'grain:inventory' %}">Inventory</a></li>
        <li class="{% nav_active request 'grain:product_list grain:vendor_list grain:category_list grain:unit_list' %} dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="{% nav_active request 'grain:product_list' %}"><a href="{% url 'grain:product_list' %}">Products</a></li>
            <li class="{% nav_active request 'grain:category_list' %}"><a href="{% url 'grain:category_list' %}">Categories</a></li>
            <li class="{% nav_active request 'grain:vendor_list' %}"><a href="{% url 'grain:vendor_list' %}">Vendors</a></li>
            <li class="{% nav_active request 'grain:unit_list' %}"><a href="{% url 'grain:unit_list' %}">Units</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-pawn" aria-hidden="true"></span> {% get_profile_name request.session.grain_active_user_profile %} <span class="caret"></span></a>
          {% get_profile_list request.user %}
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/grain/unit_form.html
{% extends "grain/base.html" %}
{% load bootstrap3 %}

{% block title %}Grain: New Unit{% endblock %}

{% block content %}
<h1>New Unit</h1>

<div class="col-md-4">
  <form method="post" action="{% url 'grain:unit_create' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Create</button>
    {% endbuttons %}
  </form>
</div>
{% endblock content %}